AWSTemplateFormatVersion: "2010-09-09"
Description: "Secret AWS"

Parameters:
  DBDescriptionParameter:
    Description: "Descripcion del secreto"
    Type: String

  DBNameParameter:
    Description: "Nombre del secreto"
    Type: String

  DBPasswordParameter:
    Description: "Contrase침a del usuario maestro de la base de datos"
    NoEcho: true
    Type: String

  DBUserParameter:
    Description: "Nombre de usuario del usuario maestro de la base de datos"
    Type: String

  TagsParameter:
    Description: "Etiquetas para asociar el secreto a un proyecto"
    Type: String
    AllowedValues:
         - prd
         - test
         - dev
    Default: "prd"

Resources:
  SecretManagerDB:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: !Ref DBDescriptionParameter  # Descripci칩n del secreto
      Name: !Ref DBNameParameter  # Nombre del secreto en AWS Secrets Manager
      SecretString: !Sub
        '{"username": "${DBUserParameter}", "password": "${DBPasswordParameter}"}'  # Define la cadena secreta con un nombre de usuario y la contrase침a proporcionada por el par치metro
      Tags:
           - Value: "environment"
             Key: !Ref TagsParameter  # Etiqueta para asociar el secreto a un proyecto
           
Outputs:
  SecretManagerDBArn:
    Description: "ARN del secreto almacenado en AWS Secrets Manager"
    Value: !Ref SecretManagerDB  # Muestra el ARN del secreto creado como valor de salida
